### ISSUE TITLE
MacroTools.jl fails on J1.5 due to removal of @get! from base

### ISSUE THREAD

**Issue by goedman** [FluxML/MacroTools.jl#134]
This is similar to the problem that was fixed in Requires.jl v1.0.1.

**Comment by essenciary** [comment]
Confirmed - breaks CI on Julia nightly for Genie.

**Comment by goedman** [comment]
Locally I've just copied the macro to utils.jl, which works fine, but as in Requires.jl, not sure if that is an ok solution.

**Comment by fingolfin** [comment]
This was resolved by PR #133.
