### ISSUE TITLE
Documentation deployment is broken  

### ISSUE THREAD

**Issue by mbeltagy** [FluxML/MacroTools.jl#145]
We now get `404` error on opening 
https://mikeinnes.github.io/MacroTools.jl/stable

**Comment by mbeltagy** [comment]
Looks like https://github.com/FluxML/MacroTools.jl/pull/143 fixes this.

**Comment by femtomc** [comment]
Still down for me.

**Comment by mbeltagy** [comment]
@femtomc 
You can find the docs here:
https://fluxml.ai/MacroTools.jl/stable/
I hope https://github.com/FluxML/MacroTools.jl/pull/143 gets merged... it has been a while.

**Comment by fingolfin** [comment]
I think this has been resolved and can be closed?
