### ISSUE TITLE
`isdef` always returns true

### ISSUE THREAD

**Issue by marius311** [FluxML/MacroTools.jl#154]
On 0.5.6, `isdef` returns `true` for any value. The code looks like it assumes `longdef1` returns `nothing` in some cases, but that's not what it does. Bisects down to https://github.com/FluxML/MacroTools.jl/pull/138.

**Comment by cstjean** [comment]
I remember being impressed by the [test suite](https://github.com/FluxML/MacroTools.jl/pull/138/files#diff-3483c521f73b08fdb6b00f014614cc0d69f87ea7b098a24aff838cbdc812704d) in that PR. Ha, they're all positive examples! 🙂

**Comment by cstjean** [comment]
Given that there's more discussion there, I'm going to close in favor of the dup #172
