### ISSUE TITLE
Wrong slurp flag for slurps with default args

### ISSUE THREAD

**Issue by untoreh** [FluxML/MacroTools.jl#165]
```julia
## Passes
args = splitdef(Meta.parse("f(v::Int...) = v"))[:args]
spa = splitarg(args[1])
@assert spa[3] == true 
@assert spa[4] == nothing

## Slurp fails
args = splitdef(Meta.parse("f(v::Int...=0) = v"))[:args]
spa = splitarg(args[1])
@assert spa[3] == true # This one fails, should be true
@assert spa[4] == 0
```

**Comment by cstjean** [comment]
I don't get it. What behaviour did you expect?

**Comment by untoreh** [comment]
the third assertion should pass, `v` is a slurp argument with a default value, so the third element of the tuple returned by `splitarg` should return true since it is the slurp flag

**Comment by cstjean** [comment]
Oh, ok, thanks for the edit. I agree, something's wrong here. PR welcome.
