### ISSUE TITLE
@capture(:(a.(b,c)),x_.y_) is false

### ISSUE THREAD

**Issue by PhilippeMaincon** [FluxML/MacroTools.jl#191]
First things first: `MacroTools` is very useful, thank you.

I execute `@capture(:(a.(b,c)),x_.y_)` and expect to get `a=:x` and  `y=:(b,c)`.  Instead `@capture` is `false`.

A Julia quirk (as far as I can see) is that `a.b` parses to `Expr(:. , :a, QuoteNode(:b)`, but  `a.(b,c)` parses without a `QuoteNode`.  I imagine this is what upsets the cart.  Arguably, `a.(b,c)` is not sound Julia syntax.  On the other hand, one classic use of macros is to create new syntaxes.

**Comment by cstjean** [comment]
`a.(b,c)` is broadcasting syntax (i.e. `sin.([1,2,3])`), whereas `a.b` is getproperty syntax. The two are parsed differently because they correspond to different concepts, so I would say that MacroTools is correct.

If you want to capture `.()`, you need that in your pattern too. Eg.

```julia
julia> @capture(:(sin.(x)), f_.(args__))
true
```

**Comment by PhilippeMaincon** [comment]
Aha! that explains this behaviour which I called quirky.
I think my troubles come from me wanting my macro to create a new syntax in which the dots get a Julia-incompatible meaning, and so I get at odds with the parser. I will explore another solution: in my syntax, replace the dot with a multiplication operator, we'll see.

Closed, merci.

**Comment by cstjean** [comment]
De rien!

Julia has a long list list of [binary operators](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm#L13-L30) which can be fun to mine for extra macro quirkiness.
