### ISSUE TITLE
`flatten` deletes `catch` blocks on Julia 1.10

### ISSUE THREAD

**Issue by Krastanov** [FluxML/MacroTools.jl#194]
# On 1.10 beta, the `catch` block is lost (even with `MacroTools#master`)

```
julia> using MacroTools

julia> MacroTools.flatten(quote try f() catch end end)
quote
    #= REPL[2]:1 =#
    try
        #= REPL[2]:1 =#
        f()
    end
end

julia> versioninfo()
Julia Version 1.10.0-beta1
Commit 6616549950e (2023-07-25 17:43 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 7950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
  Threads: 47 on 32 virtual cores

julia> using Pkg; Pkg.status()
Status `/tmp/Project.toml`
  [1914dd2f] MacroTools v0.5.10
```

# On 1.9 the `catch` block is preserved

```
julia> using MacroTools

julia> MacroTools.flatten(quote try f() catch end end)
quote
    #= REPL[2]:1 =#
    try
        #= REPL[2]:1 =#
        f()
    catch
    end
end

julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 7950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 32 on 32 virtual cores

julia> using Pkg; Pkg.status()
Status `/tmp/Project.toml`
  [1914dd2f] MacroTools v0.5.10
```

Reported here: https://github.com/JuliaLang/julia/issues/50710

**Comment by cstjean** [comment]
Thank you for the report! I don't have 1.10 installed. If you don't mind, could you please dig a bit deeper and figure out why it's happening? The [flatten implementation](https://github.com/FluxML/MacroTools.jl/blob/master/src/utils.jl#L454-L463) looks "obviously right" to me, so I don't understand how it ends up like this. It suggests that JuliaSyntax has a different structure for try/catch than normal julia, and so it isn't clear to me that this is MacroTools' fault.

**Comment by Krastanov** [comment]
I will look into it. It is almost certainly not MacroTool's fault, but it seemed reasonable to me to have it logged here.

**Comment by Krastanov** [comment]
It is due to the length check in `flatten1`.

On 1.9:

```
julia> :(try f() catch end).args[3].args |> length
0
```

On 1.10 beta

```
julia> :(try f() catch end).args[3].args |> length
1
```

I will for now close this issue and continue the conversation on the julia issue tracker.

**Comment by Krastanov** [comment]
Reopening as upstream Julia folks do not consider this a "breaking" change in "public" API. Will submit a PR later today.

**Comment by cstjean** [comment]
Other related bug, even on 1.9

```julia
julia> eval(MacroTools.flatten(MacroTools.striplines(:(try error() catch; false finally end))))
ERROR: 
```

This should not error. It's because `false` becomes the third argument of the `try`, and so it's like if there was no `catch` clause.
